# If false, will disable collection of metrics information by bStats for PySpigot. You may also disable bStats server-wide in the bStats config.yml under /plugins/bStats.
metrics-enabled: true
# The delay for loading scripts (in ticks) after the server finishes loading.
script-load-delay: 20
# List of relocation rules for libraries in the libs folder. Format as <pattern>|<relocated pattern>
library-relocations: []
# If true, PySpigot will log script messages to their respective log file. This value is global, and per-script options in script_options.yml overrides this value.
log-to-file: true
# The minimum log level that will be logged to a script's log file. For log level and their order, see https://docs.oracle.com/en/java/javase/11/docs/api/java.logging/java/util/logging/Level.html. This value is global, and per-script options in script_options.yml overrides this value.
min-log-level: 'INFO'
# Date/time format for timestamps in script log files, written in Java's SimpleDateFormat pattern: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/format/DateTimeFormatter.html
log-timestamp-format: 'MMM dd yyyy HH:mm:ss'
# If true, will print log messages to console every time a script is loaded, run, and unloaded.
script-action-logging: true
# If true, will log all redis events to the console and to a script's logger. If false, will only log
verbose-redis-logging: true
# The options for the underlying GraalVM engine that runs the scripts. For more information, see https://www.graalvm.org/sdk/javadoc/org/graalvm/polyglot/Engine.Builder.html
engine-options:
  # Must be set to true if using the 'python.EmulateJython' option for the engine.
  allow-experimental-options: false
  # The sandbox policy for scripts. For more information, see https://www.graalvm.org/sdk/javadoc/org/graalvm/polyglot/SandboxPolicy.html
  sandbox-policy: 'TRUSTED'
  # If true, the engine will use system-defined properties
  use-system-properties: true
  # Miscellaneous options that the engine should use. Defined as <option>,<value>. The option defined here suppresses a trivial warning message displayed on plugin load
  options:
    - 'engine.WarnInterpreterOnly,false'
# The default context options that should be used for scripts. These can be overridden by defining script-specific context options in the script-options.yml file. For more information, see https://www.graalvm.org/sdk/javadoc/org/graalvm/polyglot/Context.Builder.html
context-options:
  # The default value for all privileges
  allow-all-access: true
  # If true, allows scripts to execute external processes
  allow-create-process: true
  # If true, allows scripts to create new threads
  allow-create-thread: true
  # INHERIT allows scripts read access to the process environment, NONE does not allow scripts access to the process environment. For more information, see https://www.graalvm.org/sdk/javadoc/org/graalvm/polyglot/EnvironmentAccess.html.
  environment-access-policy: 'INHERIT'
  # Must be set to true if using the 'python.EmulateJython' option for the context.
  allow-experimental-options: true
  # Configures which constructors, methods, and fields of classes are accessible by scripts. For more information, see https://www.graalvm.org/sdk/javadoc/org/graalvm/polyglot/HostAccess.html.
  host-access-policy: 'ALL'
  # Allows a script's context to spawn inner contexts that may change option values set for the outer context.
  allow-inner-context-options: true
  # ALL allows scripts to access host I/O, NONE does not allow I/O access. For more information, see https://www.graalvm.org/sdk/javadoc/org/graalvm/polyglot/io/IOAccess.html.
  io-access-policy: 'ALL'
  # Allows scripts to access the native interface.
  allow-native-access: true
  # If true, allows for value sharing between scripts.
  allow-value-sharing: true
  # Miscellaneous options that the script's context should use. Defined as <option>,<value>. The option defined here emulates Jython for backwards compatibility.
  options:
    - 'python.EmulateJython,true'
  # The sandbox policy for the script's context. For more information, see https://www.graalvm.org/sdk/javadoc/org/graalvm/polyglot/SandboxPolicy.html
  sandbox-policy: 'TRUSTED'
# Advanced debug options for scripts
debug-options:
  # If true, will print stack traces for all script-related exceptions to the server console
  print-stack-traces: false
  # If ture, will suppress notifications that the plugin version is outdated
  suppress-update-messages: false
  # If false, the pyspigot.py file will *not* be automatically replaced with the most recent version (from the pyspigot JAR) on server start if a change is detected. It is recommended to keep this enabled in the event a plugin update comes with an updated pyspigot.py file.
  auto-pyspigot-lib-update-enabled: true
messages:
  plugin-prefix: '&8[&6PySpigot&8] &r'
  enter-playground-mode: '&aYou are now in playground mode. All messages you type will be read and interpreted as Python. To exit playground mode, call exit() or type /pyspigot playground again.'
  exit-playground-mode: '&cYou have exited playground mode.'